### PR TITLE
Adding Debian support

### PR DESCRIPTION
**Pull request by BillWeiss**
I really wanted this to work in Debian, so I hacked in some cases around $::osfamily .  While I was in there I moved the /etc/cron.d/sa-update drop into a cron {} resource.  It works pretty well here, and I'm fairly sure I didn't break the existing RHEL (I assume) compatibility.  I also added a bail-out for $::osfamily that isn't Debian or RedHat.

### CODE REVIEW

**Comment by BillWeiss** [comment]
After this point is some puppet-lint inspired bikeshedding.  No changes in content, just formatting.

**Comment by bobtfish** [comment]
Can this get merged and see a new forge release?

**Comment by BillWeiss** [comment]
I'd be willing to fork this and get a separate module on the forge, I guess, if it's not maintained.

**Comment by BillWeiss** [comment]
As you can probably see from the commits, I've forked this to submit to the forge.  This probably messes up my pull request, but I don't know enough git to not do that :(

**Comment by BillWeiss** [comment]
I don't maintain any Puppet code anymore, so I'm going to close this out

**Pull request closed without merging**
